version: "3.8"

services:
  app:
    build: .
    container_name: linkedin_insights_service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/linked_microservice_insights
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    container_name: linkedin_insights_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
